name: desc-drp-stack-weekly latest

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
      - name: Check Disk Space
        run: df -h && sudo apt-get clean && df -h 
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout desc-drp-stack
        uses: actions/checkout@v2
        with:
          ref: weekly
          fetch-depth: 1
      - name : Docker prune
        run: sudo docker system prune && df -h 
      - name : Get weekly number and date 
        run: |
          echo "LSST_TAG=w_2021_$(date "+%U" -d "$end_date+3 days")" >> $GITHUB_ENV
          echo "DATE_TAG=$(date "+%F")" >> $GITHUB_ENV
      - name: do docker build
        run: docker build --no-cache --build-arg LSST_TAG=${{env.LSST_TAG}} -t lsstdesc/desc-drp-stack:weekly -f $GITHUB_WORKSPACE/Dockerfile . 
      - name: test numba
        run: docker run --rm lsstdesc/desc-drp-stack:weekly /bin/sh -c "source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && python -c 'import numba'"
      - name: Docker push
        run: docker push lsstdesc/desc-drp-stack:weekly
      - name: tag versions
        run: |
          docker tag lsstdesc/desc-drp-stack:weekly lsstdesc/desc-drp-stack:${{env.LSST_TAG}}-${{env.DATE_TAG}}
          docker push lsstdesc/desc-drp-stack:${{env.LSST_TAG}}-${{env.DATE_TAG}}
          docker tag lsstdesc/desc-drp-stack:weekly lsstdesc/desc-drp-stack:${{env.LSST_TAG}}
          docker push lsstdesc/desc-drp-stack:${{env.LSST_TAG}}
