name: desc-drp-stack latest

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - name: Check Disk Space
        run: df -h && sudo apt-get clean && df -h 
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout desc-drp-stack
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: do docker build
        run: docker build --no-cache -t lsstdesc/desc-drp-stack:latest -f $GITHUB_WORKSPACE/Dockerfile . 
      - name: test numba
        run: docker run --rm lsstdesc/desc-drp-stack:latest /bin/sh -c "source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && python -c 'import numba'"
      - name: Docker push
        run: docker push lsstdesc/desc-drp-stack:latest
       
